version: "3.2"
services:
  mysql:
    ports:
    - 3306:3306
    image: mysql:1.0.0
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: 'root'
      MYSQL_PASS: '123456'
      MYSQL_DATABASE: 'optical_module'
    volumes:
      - /mysqlom/data:/var/lib/mysql
      - /mysqlom/conf/my.cnf:/etc/mysql/my.cnf
      - /mysqlom/init:/docker-entrypoint-initdb.d/
      - /mysqlom/run:/mysql/run
    restart: unless-stopped
#  nginx:
#    ports:
#    - "8090:8090"
#    - "8088:8088"
#    image: nginx:1.0.0
#    hostname: nginx
#    container_name: nginx
#    volumes:
#      - /opt/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
#      - /data/nginx/log:/var/log/nginx
#      - /opt/nginx:/opt/nginx
#      - /www/om/:/usr/share/nginx/html
#    restart: unless-stopped
#
#  om:
#    ports:
#    - 8089:8089
#    image: omserver:1.0.0
#    hostname: omserver
#    container_name: omserver
#    links:
#      - nginx
#      - mysql
#    restart: unless-stopped
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 3
#        window: 120s
#      resources:
#        limits:
#          cpus: '4'
#          memory: 8G
#        reservations:
#          cpus: '0.2'
#          memory: 100M
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=optical_module
#      - MYSQL_IP=mysql
#      - MYSQL_PORT=3306
#      - MYSQL_USER=root
#      - MYSQL_PWD=root
#      - SSO_IP=10.114.134.79
#      - SSO_PORT=10380
#      - SSO_AUTH_CLIENT_ID=GuangMoKuai
#      - SSO_AUTH_CLIENT_PASSWORD=666666
#      - GAEA_OPERATORDASHBOARD_IP=10.114.134.79
#      - GAEA_OPERATORDASHBOARD_PORT=8081
#      - GAEA_CHAINCODE_ID=5f68841c61e298006747da0c
#      - GAEA_CHANNEL_ID=5f685fe99d5f2d00553497a8
#      - PORT=8089
#    cap_add:
#      - SYS_PTRACE
